version: "3"
services:

  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    links:
      - "postgres"
    ports:
      - 6969:6969
    environment:
      - DATABASE_URL=${DATABASE_URL}

  postgres:
    image: "library/postgres:11.1"
    environment:
      POSTGRES_USER: "dgadmin"
      POSTGRES_PASSWORD: "dgserver33"
    expose:
      - "5432"