version: "3"
services:

  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - 6969:6969
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis

  postgres:
    image: "library/postgres:11.1"
    environment:
      POSTGRES_USER: "dgadmin"
      POSTGRES_PASSWORD: "dgserver33"
    expose:
      - "5432"

  redis:
    image: "library/redis:5.0.3"
    volumes:
      - redis_data:/data

  volumes:
    redis_data:
    