"""empty message

Revision ID: 1b2828f72f15
Revises: 4c7cda65ab23
Create Date: 2019-01-02 17:29:58.817932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2828f72f15'
down_revision = '4c7cda65ab23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_name', sa.String(), nullable=False))
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    op.alter_column('users', 'phone_num',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_num',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=35),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=35),
               nullable=True)
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('projects', 'project_name')
    # ### end Alembic commands ###