"""empty message

Revision ID: 4c7cda65ab23
Revises: ac0c976549b4
Create Date: 2019-01-01 22:35:41.209200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7cda65ab23'
down_revision = 'ac0c976549b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###