"""empty message

Revision ID: 56c39b5eeffb
Revises: 
Create Date: 2018-12-29 01:05:37.050609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c39b5eeffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=35), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=35), nullable=True))
    op.add_column('users', sa.Column('perishable_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('token_expires', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['perishable_token'])
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token_expires')
    op.drop_column('users', 'perishable_token')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'birthday')
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    # ### end Alembic commands ###