"""empty message

Revision ID: ac0c976549b4
Revises: 56c39b5eeffb
Create Date: 2019-01-01 18:32:03.208900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac0c976549b4'
down_revision = '56c39b5eeffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('password_salt', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('first_name', sa.String(length=35), nullable=False),
    sa.Column('last_name', sa.String(length=35), nullable=False),
    sa.Column('phone_num', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=74), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_tier', sa.Integer(), nullable=False),
    sa.Column('subscription_period', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categories', sa.PickleType(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('_permissions', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_logged_in', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('password_salt', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_num', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_perishable_token_key', 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'projects', ['project_id'], ['id'])
    op.drop_column('users', 'perishable_token')
    op.drop_column('users', 'token_expires')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('perishable_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint('users_perishable_token_key', 'users', ['perishable_token'])
    op.drop_column('users', 'project_id')
    op.drop_column('users', 'phone_num')
    op.drop_column('users', 'password_salt')
    op.drop_column('users', 'password')
    op.drop_column('users', 'last_updated')
    op.drop_column('users', 'last_logged_in')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', '_permissions')
    op.drop_table('projects')
    op.drop_table('admins')
    # ### end Alembic commands ###