"""empty message

Revision ID: 18fdc45d4a1b
Revises: 4d1fd0769f25
Create Date: 2019-01-23 06:56:37.036550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fdc45d4a1b'
down_revision = '4d1fd0769f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###