"""empty message

Revision ID: 2b9360f0b424
Revises: 5b78aff5a7b5
Create Date: 2019-01-20 02:00:13.595095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9360f0b424'
down_revision = '5b78aff5a7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', '_suppliers')
    op.add_column('suppliers', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'project_id')
    op.add_column('projects', sa.Column('_suppliers', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###