"""empty message

Revision ID: 820de4b26117
Revises: f04d43490853
Create Date: 2019-01-22 03:40:17.484923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '820de4b26117'
down_revision = 'f04d43490853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internal_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventory_products', sa.Column('internal_name_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_products', 'internal_names', ['internal_name_id'], ['id'])
    op.drop_column('projects', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('categories', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory_products', type_='foreignkey')
    op.drop_column('inventory_products', 'internal_name_id')
    op.drop_table('internal_names')
    op.drop_table('categories')
    # ### end Alembic commands ###