"""empty message

Revision ID: f04d43490853
Revises: 2b9360f0b424
Create Date: 2019-01-20 04:37:22.174761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04d43490853'
down_revision = '2b9360f0b424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###